pre_path_scene_img = "img//element//zhanyi//"
scene_image_path = []
zhanyi_scene_checkpoint = [(350,160),(550,160),(600,160),(650,160),(700,160),(77,158)]
dummy = None
scene_1_1 = ("zhanyi_1_1.png","zhanyi_1_2.png","zhanyi_1_3.png","zhanyi_1_4.png","zhanyi_1_5.png","zhanyi_type_putong.png")
scene_1_2 = ("zhanyi_2_1.png","zhanyi_2_2.png","zhanyi_2_3.png","zhanyi_2_4.png","zhanyi_2_5.png","zhanyi_type_putong.png")
scene_1_3 = ("zhanyi_3_1.png","zhanyi_3_2.png","zhanyi_3_3.png","zhanyi_3_4.png","zhanyi_3_5.png","zhanyi_type_putong.png")
scene_1_4 = ("zhanyi_4_1.png","zhanyi_4_2.png","zhanyi_4_3.png","zhanyi_4_4.png","zhanyi_4_5.png","zhanyi_type_putong.png")
scene_1_5 = ("zhanyi_5_1.png","zhanyi_5_2.png","zhanyi_5_3.png","zhanyi_5_4.png","zhanyi_5_5.png","zhanyi_type_putong.png")
scene_1_6 = ("zhanyi_6_1.png","zhanyi_6_2.png","zhanyi_6_3.png","zhanyi_6_4.png","zhanyi_6_5.png","zhanyi_type_putong.png")
scene_1_7 = ("zhanyi_7_1.png","zhanyi_7_2.png","zhanyi_7_3.png","zhanyi_7_4.png","zhanyi_7_5.png","zhanyi_type_putong.png")
scene_1_8 = ("zhanyi_8_1.png","zhanyi_8_2.png","zhanyi_8_3.png","zhanyi_8_4.png","zhanyi_8_5.png","zhanyi_type_putong.png")
scene_1_9 = ("zhanyi_9_1.png","zhanyi_9_2.png","zhanyi_9_3.png","zhanyi_9_4.png","zhanyi_9_5.png","zhanyi_type_putong.png")
scene_2_1 = ("zhanyi_1_1.png","zhanyi_1_2.png","zhanyi_1_3.png","zhanyi_1_4.png","zhanyi_1_5.png","zhanyi_type_jingying.png")
scene_2_2 = ("zhanyi_2_1.png","zhanyi_2_2.png","zhanyi_2_3.png","zhanyi_2_4.png","zhanyi_2_5.png","zhanyi_type_jingying.png")
scene_2_3 = ("zhanyi_3_1.png","zhanyi_3_2.png","zhanyi_3_3.png","zhanyi_3_4.png","zhanyi_3_5.png","zhanyi_type_jingying.png")
scene_2_4 = ("zhanyi_4_1.png","zhanyi_4_2.png","zhanyi_4_3.png","zhanyi_4_4.png","zhanyi_4_5.png","zhanyi_type_jingying.png")
scene_2_5 = ("zhanyi_5_1.png","zhanyi_5_2.png","zhanyi_5_3.png","zhanyi_5_4.png","zhanyi_5_5.png","zhanyi_type_jingying.png")
scene_2_6 = ("zhanyi_6_1.png","zhanyi_6_2.png","zhanyi_6_3.png","zhanyi_6_4.png","zhanyi_6_5.png","zhanyi_type_jingying.png")
scene_2_7 = ("zhanyi_7_1.png","zhanyi_7_2.png","zhanyi_7_3.png","zhanyi_7_4.png","zhanyi_7_5.png","zhanyi_type_jingying.png")
scene_2_8 = ("zhanyi_8_1.png","zhanyi_8_2.png","zhanyi_8_3.png","zhanyi_8_4.png","zhanyi_8_5.png","zhanyi_type_jingying.png")
scene_2_9 = ("zhanyi_9_1.png","zhanyi_9_2.png","zhanyi_9_3.png","zhanyi_9_4.png","zhanyi_9_5.png","zhanyi_type_jingying.png")
scene_3_7 = ("zhanyi_7_1.png","zhanyi_7_2.png","zhanyi_7_3.png","zhanyi_7_4.png","zhanyi_7_5.png","zhanyi_type_tuandui.png")
scene_3_8 = ("zhanyi_8_1.png","zhanyi_8_2.png","zhanyi_8_3.png","zhanyi_8_4.png","zhanyi_8_5.png","zhanyi_type_tuandui.png")
scene_3_9 = ("zhanyi_9_1.png","zhanyi_9_2.png","zhanyi_9_3.png","zhanyi_9_4.png","zhanyi_9_5.png","zhanyi_type_tuandui.png")
scene_image_path.append(scene_1_1)
scene_image_path.append(scene_1_2)
scene_image_path.append(scene_1_3)
scene_image_path.append(scene_1_4)
scene_image_path.append(scene_1_5)
scene_image_path.append(scene_1_6)
scene_image_path.append(scene_1_7)
scene_image_path.append(scene_1_8)
scene_image_path.append(scene_1_9)

scene_image_path.append(scene_2_1)
scene_image_path.append(scene_2_2)
scene_image_path.append(scene_2_3)
scene_image_path.append(scene_2_4)
scene_image_path.append(scene_2_5)
scene_image_path.append(scene_2_6)
scene_image_path.append(scene_2_7)
scene_image_path.append(scene_2_8)
scene_image_path.append(scene_2_9)

scene_image_path.append(dummy)
scene_image_path.append(dummy)
scene_image_path.append(dummy)
scene_image_path.append(dummy)
scene_image_path.append(dummy)
scene_image_path.append(dummy)
scene_image_path.append(scene_3_7)
scene_image_path.append(scene_3_8)
scene_image_path.append(scene_3_9)